# Generated by Django 5.0.3 on 2024-03-09 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reservacion', models.IntegerField()),
                ('nombre_titular', models.CharField(max_length=512)),
                ('edad', models.IntegerField()),
                ('pais_origen', models.CharField(max_length=512)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'Ingles'), ('fr', 'Frances'), ('de', 'Aleman'), ('cn', 'Mandarin'), ('ot', 'Otro')], max_length=2)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('no_adultos', models.IntegerField()),
                ('no_menores', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
